package com.example.ajouevent.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Type {

    AIMOBILITYENGINEERING("AIMobilityEngineering"),
    AJOUNORMAL("AjouNormal"),
    AJOUSCHOLARSHIP("AjouScholarship"),
    APPLIEDARTIFICIALINTELLIGENCE("AppliedArtificialIntelligence"),
    APPLIEDCHEMISTRYBIOLOGICALENGINEERING("AppliedChemistryBiologicalEngineering"),
    ARCHITECTURE("Architecture"),
    BIOLOGICALSCIENCE("BiologicalScience"),
    BUSINESS("Business"),
    BUSINESSADMINISTRATION("BusinessAdministration"),
    CHEMICALENGINEERING("ChemicalEngineering"),
    CHEMISTRY("Chemistry"),
    CIVILSYSTEMSENGINEERING("CivilSystemsEngineering"),
    COMPUTINGINFORMATICS("ComputingInformatics"),
    CULTURECONTENTS("CultureContents"),
    CYBERSECURITY("CyberSecurity"),
    DASAN("Dasan"),
    DIGITALMEDIA("DigitalMedia"),
    ECONOMICS("Economics"),
    ELECTRICALCOMPUTERENGINEERING("ElectricalComputerEngineering"),
    ENGINEERING("Engineering"),
    ENGLISHLANGUAGELITERATURE("EnglishLanguageLiterature"),
    ENVIRONMENTALSAFETYENGINEERING("EnvironmentalSafetyEngineering"),
    FINANCIALENGINEERING("FinancialEngineering"),
    FRENCHLANGUAGELITERATURE("FrenchLanguageLiterature"),
    GLOBALBUSINESS("GlobalBusiness"),
    GRADUATE("Graduate"),
    HISTORY("History"),
    HUMANITIES("Humanities"),
    INDUSTRIALENGINEERING("IndustrialEngineering"),
    INFORMATIONTECHNOLOGY("InformationTechnology"),
    INTEGRATIVESYSTEMSENGINEERING("IntegrativeSystemsEngineering"),
    INTELLIGENCESEMICONDUCTORENGINEERING("IntelligenceSemiconductorEngineering"),
    INTERNATIONAL("International"),
    KOREANLANGUAGELITERATURE("KoreanLanguageLiterature"),
    MANAGEMENTINTELLIGENCE("ManagementIntelligence"),
    MATERIALSSCIENCEENGINEERING("MaterialsScienceEngineering"),
    MATHMATICS("Mathmatics"),
    MECHANICALENGINEERING("MechanicalEngineering"),
    MEDICINE("Medicine"),
    MILITARYDIGITALCONVERGENCE("MilitaryDigitalConvergence"),
    NATURALSCIENCE("NaturalScience"),
    NURSING("Nursing"),
    PHARMACY("Pharmacy"),
    PHYSICS("Physics"),
    POLITICALSCIENCEDIPLOMACY("PoliticalScienceDiplomacy"),
    PSYCHOLOGY("Psychology"),
    PUBLICADMINISTRATION("PublicAdministration"),
    SOCIALSCIENCE("SocialScience"),
    SOCIOLOGY("Sociology"),
    SOFTWARE("Software"),
    SPORTSLEISURESTUDIES("SportsLeisureStudies"),
    TRANSPORTATIONSYSTEMSENGINEERING("TransportationSystemsEngineering"),
    TEST("Test");



    private final String englishTopic;


    // AIMobilityEngineering,
    // AjouNormal,
    // AjouScholarship,
    // AppliedArtificialIntelligence,
    // AppliedChemistryBiologicalEngineering,
    // Architecture,
    // BiologicalScience,
    // Business,
    // BusinessAdministration,
    // ChemicalEngineering,
    // Chemistry,
    // CivilSystemsEngineering,
    // ComputingInformatics,
    // CultureContents,
    // CyberSecurity,
    // Dasan,
    // DigitalMedia,
    // Economics,
    // ElectricalComputerEngineering,
    // Engineering,
    // EnglishLanguageLiterature,
    // EnvironmentalSafetyEngineering,
    // FinancialEngineering,
    // FrenchLanguageLiterature,
    // GlobalBusiness,
    // Graduate,
    // History,
    // Humanities,
    // IndustrialEngineering,
    // InformationTechnology,
    // IntegrativeSystemsEngineering,
    // IntelligenceSemiconductorEngineering,
    // International,
    // KoreanLanguageLiterature,
    // ManagementIntelligence,
    // MaterialsScienceEngineering,
    // Mathmatics,
    // MechanicalEngineering,
    // Medicine,
    // MilitaryDigitalConvergence,
    // NaturalScience,
    // Nursing,
    // Pharmacy,
    // Physics,
    // PoliticalScienceDiplomacy,
    // Psychology,
    // PublicAdministration,
    // SocialScience,
    // Sociology,
    // Software,
    // SportsLeisureStudies,
    // TransportationSystemsEngineering
    // AIMOBILITYENGINEERING,
    // AJOUNORMAL,
    // AJOUSCHOLARSHIP,
    // APPLIEDARTIFICIALINTELLIGENCE,
    // APPLIEDCHEMISTRYBIOLOGICALENGINEERING,
    // ARCHITECTURE,
    // BIOLOGICALSCIENCE,
    // BUSINESS,
    // BUSINESSADMINISTRATION,
    // CHEMICALENGINEERING,
    // CHEMISTRY,
    // CIVILSYSTEMSENGINEERING,
    // COMPUTINGINFORMATICS,
    // CULTURECONTENTS,
    // CYBERSECURITY,
    // DASAN,
    // DIGITALMEDIA,
    // ECONOMICS,
    // ELECTRICALCOMPUTERENGINEERING,
    // ENGINEERING,
    // ENGLISHLANGUAGELITERATURE,
    // ENVIRONMENTALSAFETYENGINEERING,
    // FINANCIALENGINEERING,
    // FRENCHLANGUAGELITERATURE,
    // GLOBALBUSINESS,
    // GRADUATE,
    // HISTORY,
    // HUMANITIES,
    // INDUSTRIALENGINEERING,
    // INFORMATIONTECHNOLOGY,
    // INTEGRATIVESYSTEMSENGINEERING,
    // INTELLIGENCESEMICONDUCTORENGINEERING,
    // INTERNATIONAL,
    // KOREANLANGUAGELITERATURE,
    // MANAGEMENTINTELLIGENCE,
    // MATERIALSSCIENCEENGINEERING,
    // MATHMATICS,
    // MECHANICALENGINEERING,
    // MEDICINE,
    // MILITARYDIGITALCONVERGENCE,
    // NATURALSCIENCE,
    // NURSING,
    // PHARMACY,
    // PHYSICS,
    // POLITICALSCIENCEDIPL0MACY,
    // PSYCHOLOGY,
    // PUBLICADMINISTRATION,
    // SOCIALSCIENCE,
    // SOCIOLOGY,
    // SOFTWARE,
    // SPORTSLEISURESTUDIES,
    // TRANSPORTATIONSYSTEMSENGINEERING
}
