name: deploy
run-name: Running
on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: ajouevent-cicd
  AWS_CODE_DEPLOY_APPLICATION: ajouevent-be
  AWS_CODE_DEPLOY_GROUP: ajouevent-be

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:
    - name: production 브랜치로 이동
      uses: actions/checkout@v3
      with:
        ref: production

    - name: JDK 21 설치
      uses: actions/setup-java@v3
      with:
        java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build and Test
        run: ./gradlew build test